### ISSUE TITLE
Examples/consumer.hs connects and exits soon due to error

### ISSUE THREAD

**Issue by ghost** [tom-pang/hafka#2]
My Kafka, zookeeper servers are up and running on localhost. then, I ran Examples/consumer.hs using runhaskell command. It establishes the connection but crashes immediately and comes out of the wait queue. The error message is

``` haskell
Consumer.hs: Network/Kafka/Consumer.hs:67:7-57: Irrefutable pattern failed for pattern (Data.Either.Right dataLength)
```

The code @Network/Kafka/Consumer.hs#ln67 is

``` haskell
readDataResponse h handler = do
    rawLength <- h 4
    let (Right dataLength) = runGet getDataLength rawLength
```

**Comment by AJFarmar** [comment]
The problem is, the code `runGet getDataLength rawLength` is returning something with the structure `Left xyz`. Because your `let` expression assumes that it is something of the structure `Right xyz`, it fails. 

To fix this, I would use the function `either :: (a -> c) -> (b -> c) -> Either a b -> c` to make a failsafe way of extracting a value from an `Either` type.

**Comment by tom-pang** [comment]
This project is unmaintained.

**Comment by tom-pang** [comment]
(if you wanna fork it and take over maintainership, feel free)

**Comment by tom-pang** [comment]
(but I never finished it even)
